In [9]:
import pandas as pd

df = pd.read_csv(file_path, encoding='latin-1')

df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

In [12]:
df.tail()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
180514,TRANSFER,6,4,-107.96,161.87,Late delivery,1,76,Women's Clothing,Caguas,...,1,215.82,161.87,-107.96,Southeast Asia,Java Occidental,PROCESSING,Summer dresses,215.82,Standard Class
180515,DEBIT,2,4,-126.56,172.66,Advance shipping,0,76,Women's Clothing,Plainfield,...,1,215.82,172.66,-126.56,Southeast Asia,Java Occidental,COMPLETE,Summer dresses,215.82,Standard Class
180516,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,...,1,327.75,314.64,91.25,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,Standard Class
180517,PAYMENT,4,4,1.53,10.91,Shipping on time,0,74,Toys,Berwyn,...,1,11.54,10.91,1.53,Southeast Asia,Java Occidental,PENDING_PAYMENT,Toys,11.54,Standard Class
180518,CASH,1,0,9.79,34.98,Late delivery,1,75,Video Games,Miami,...,1,39.75,34.98,9.79,Oceania,Queensland,CLOSED,Fighting video games,39.75,Same Day

In [17]:
 # Cheacking the  null values in the Dataset
missing_values = df.isnull().sum()
missing_values_percentage = (missing_values / len(df)) * 100
print(f"The Number of Missing Values : {missing_values}")
print(f"The Percentage O=of Missing values : {missing_values_percentage}")

The Number of Missing Values : Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Fname                   0
Customer Id                      0
Customer Lname                   8
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 3
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Product Name                     0
Product Price                    0
Shipping Mode                    0
dtype: int64
The Percentage O=of Missing values : Type                             0.000000
Days for shipping (real)         0.000000
Days for shipment (scheduled)    0.000000
Benefit per order                0.000000
Sales per customer               0.000000
Delivery Status                  0.000000
Late_delivery_risk               0.000000
Category Id                      0.000000
Category Name                    0.000000
Customer City                    0.000000
Customer Country                 0.000000
Customer Fname                   0.000000
Customer Id                      0.000000
Customer Lname                   0.004432
Customer Segment                 0.000000
Customer State                   0.000000
Customer Street                  0.000000
Customer Zipcode                 0.001662
Department Id                    0.000000
Department Name                  0.000000
Latitude                         0.000000
Longitude                        0.000000
Market                           0.000000
Order City                       0.000000
Order Country                    0.000000
Order Customer Id                0.000000
Order Item Discount              0.000000
Order Item Discount Rate         0.000000
Order Item Product Price         0.000000
Order Item Profit Ratio          0.000000
Order Item Quantity              0.000000
Sales                            0.000000
Order Item Total                 0.000000
Order Profit Per Order           0.000000
Order Region                     0.000000
Order State                      0.000000
Order Status                     0.000000
Product Name                     0.000000
Product Price                    0.000000
Shipping Mode                    0.000000
dtype: float64

In [19]:
missing = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': (df.isnull().sum()/len(df))*100
})

print(missing[missing['Missing Values'] > 0])

                  Missing Values  Percentage
Customer Lname                 8    0.004432
Customer Zipcode               3    0.001662

In [20]:
# Remove rows with missing values
df = df.dropna()

# Verify
print(df.isnull().sum())

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Fname                   0
Customer Id                      0
Customer Lname                   0
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 0
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Product Name                     0
Product Price                    0
Shipping Mode                    0
dtype: int64

In [21]:
missing = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': (df.isnull().sum()/len(df))*100
})

print(missing[missing['Missing Values'] > 0])

Empty DataFrame
Columns: [Missing Values, Percentage]
Index: []

In [22]:
# checking duplicate rows in the dataset
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

Number of duplicate rows: 0

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 180508 entries, 0 to 180518
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180508 non-null  str
 1   Days for shipping (real)       180508 non-null  int64
 2   Days for shipment (scheduled)  180508 non-null  int64
 3   Benefit per order              180508 non-null  float64
 4   Sales per customer             180508 non-null  float64
 5   Delivery Status                180508 non-null  str
 6   Late_delivery_risk             180508 non-null  int64
 7   Category Id                    180508 non-null  int64
 8   Category Name                  180508 non-null  str
 9   Customer City                  180508 non-null  str
 10  Customer Country               180508 non-null  str
 11  Customer Fname                 180508 non-null  str
 12  Customer Id                    180508 non-null  int64
 13  Customer Lname                 180508 non-null  str
 14  Customer Segment               180508 non-null  str
 15  Customer State                 180508 non-null  str
 16  Customer Street                180508 non-null  str
 17  Customer Zipcode               180508 non-null  float64
 18  Department Id                  180508 non-null  int64
 19  Department Name                180508 non-null  str
 20  Latitude                       180508 non-null  float64
 21  Longitude                      180508 non-null  float64
 22  Market                         180508 non-null  str
 23  Order City                     180508 non-null  str
 24  Order Country                  180508 non-null  str
 25  Order Customer Id              180508 non-null  int64
 26  Order Item Discount            180508 non-null  float64
 27  Order Item Discount Rate       180508 non-null  float64
 28  Order Item Product Price       180508 non-null  float64
 29  Order Item Profit Ratio        180508 non-null  float64
 30  Order Item Quantity            180508 non-null  int64
 31  Sales                          180508 non-null  float64
 32  Order Item Total               180508 non-null  float64
 33  Order Profit Per Order         180508 non-null  float64
 34  Order Region                   180508 non-null  str
 35  Order State                    180508 non-null  str
 36  Order Status                   180508 non-null  str
 37  Product Name                   180508 non-null  str
 38  Product Price                  180508 non-null  float64
 39  Shipping Mode                  180508 non-null  str
dtypes: float64(13), int64(8), str(19)
memory usage: 92.0 MB

In [26]:

df.describe().T

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180508.0,3.497673,1.623743,0.000000,2.000000,3.000000,5.000000,6.000000
Days for shipment (scheduled),180508.0,2.931837,1.374457,0.000000,2.000000,4.000000,4.000000,4.000000
Benefit per order,180508.0,21.971563,104.433860,-4274.980000,7.000000,31.520000,64.800000,911.800000
Sales per customer,180508.0,183.101749,120.041576,7.490000,104.380000,163.990000,247.400000,1939.990000
Late_delivery_risk,180508.0,0.548297,0.497663,0.000000,0.000000,1.000000,1.000000,1.000000
Category Id,180508.0,31.849270,15.637996,2.000000,18.000000,29.000000,45.000000,76.000000
Customer Id,180508.0,6690.778857,4162.304984,1.000000,3258.000000,6456.000000,9779.000000,20757.000000
Customer Zipcode,180508.0,35920.246698,37542.214613,603.000000,725.000000,19380.000000,78202.500000,99205.000000
Department Id,180508.0,5.443454,1.629175,2.000000,4.000000,5.000000,7.000000,12.000000
Latitude,180508.0,29.719858,9.813737,-33.937553,18.265432,33.144863,39.279617,48.781933
Longitude,180508.0,-84.914449,21.432290,-158.025986,-98.446312,-76.840759,-66.370583,115.263077
Order Customer Id,180508.0,6690.778857,4162.304984,1.000000,3258.000000,6456.000000,9779.000000,20757.000000
Order Item Discount,180508.0,20.663998,21.800753,0.000000,5.400000,14.000000,29.990000,500.000000
Order Item Discount Rate,180508.0,0.101668,0.070416,0.000000,0.040000,0.100000,0.160000,0.250000
Order Item Product Price,180508.0,141.222135,139.726957,9.990000,50.000000,59.990000,199.990000,1999.990000
Order Item Profit Ratio,180508.0,0.120639,0.466806,-2.750000,0.080000,0.270000,0.360000,0.500000
Order Item Quantity,180508.0,2.127706,1.453469,1.000000,1.000000,1.000000,3.000000,5.000000
Sales,180508.0,203.765492,132.270786,9.990000,119.980000,199.920000,299.950000,1999.990000
Order Item Total,180508.0,183.101749,120.041576,7.490000,104.380000,163.990000,247.400000,1939.990000
Order Profit Per Order,180508.0,21.971563,104.433860,-4274.980000,7.000000,31.520000,64.800000,911.800000
Product Price,180508.0,141.222135,139.726957,9.990000,50.000000,59.990000,199.990000,1999.990000

In [27]:
# Save the cleaned dataset as a CSV file
df.to_csv("APL_Logistics_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully as 'APL_Logistics_Cleaned.csv'")

Cleaned dataset saved successfully as 'APL_Logistics_Cleaned.csv'